FROM docker.io/oven/bun:1.3-slim
WORKDIR /app
COPY package.json package.json
COPY bun.lock bun.lock
RUN bun install --frozen-lockfile
COPY ./src ./src
COPY polyfill.js polyfill.js
ENV NODE_ENV=production
EXPOSE 3001
CMD ["bun", "run", "--preload", "./polyfill.js", "src/worker.ts"]