FROM docker.io/oven/bun:1.2-slim

WORKDIR /app

COPY package.json package.json
COPY bun.lock bun.lock

RUN bun install 

COPY ./src ./src

ENV NODE_ENV=production

EXPOSE 3001

CMD ["bun", "--preload", "./polyfill.js", "run", "src/worker.ts"]
